databases:
  - name: learning_log
    databaseName: learning_log
    user: learning_log

services:
  - type: web
    name: learning_log
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn learning_log.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "learning_log.settings"
      - key: DATABASE_URL
        fromDatabase:
          name: learning_log
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
